version: '3'

services:
    api:
        image: swcardgameapi
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - '5000:5000'
        environment:
            ASPNETCORE_URLS: http://*:5000/
        depends_on:
            - 'postgres'
        networks:
            - swcardgame-network
    frontend:
        image: swcardgamefrontend
        build:
            context: ./react-client
            dockerfile: ./Dockerfile
        ports:
            - '5500:80'
        depends_on:
            - 'api'
        networks:
            - swcardgame-network
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: docker
        networks:
            - swcardgame-network
networks:
    swcardgame-network:
        driver: bridge
